spring:
       application:
               name: interesse-service
       datasource:
             url: jdbc:mysql://localhost:3306/imoveis
             username: root
             password: 
       jpa:
             hibernate:
                        ddlAuto: update
             properties:
                        hibernate:
                                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
             showSql: true
server:
       port: 6062
eureka:
       client:
              serviceUrl:
                            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
                            instance:
                                   preferIpAddress: true